### PR TITLE
updating a few lingering print statements

### PR DESCRIPTION
**Pull request by slremy**

### CODE REVIEW

**Comment by dhardy** [comment]
Is this for Python 3 compatibilty? If so, the first line of each file should be updated from `python2` and it would make more sense to use the [`2to3` automated conversion tool](https://docs.python.org/2/library/2to3.html).

PS I can do this myself in a couple of minutes if you like. Not sure what the goal is though. Are you using these scripts yourself?

**Comment by dhardy** [comment]
Okay, but please fix the very first line of the files, which still says `#!/usr/bin/env python2` (just replace 2 with 3). This is important on Linux to make the script executable.

**Comment by slremy** [comment]
I thought I was just in to make a few small changes, but python3 is making life a bit sticky. I ran into a bit of trouble getting ```readoutput.py``` to play nice with the changes to the `io` module. 
I think I need about an hour or so to make thing right. Sorry this is taking so long!

**Comment by dhardy** [comment]
Looks good to my inexpert Python eyes. Shall I merge?

**Comment by dhardy** [comment]
Superceded by #8.

**Pull request closed without merging**
